index:
    path: /
    defaults: { _controller: 'App\Controller\BinanceController::webHookTelegram' }
#    defaults: { _controller: 'App\Controller\BinanceController::temp' }

telegram:
    path: /telegram
    defaults: { _controller: 'App\Controller\TelegramController::setDomainName' }


websocket:
    path: /websocket
    defaults: { _controller: 'App\Controller\BinanceController::testWebsocket' }
